/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary": "#ffffff",
        "surface-variant": "#e4e2e2",
        "on-secondary-fixed-variant": "#005232",
        "primary-container": "#002f6c",
        "on-primary-fixed-variant": "#224583",
        "background": "#111827", /* Changed to Dark Mode Ambient */
        "primary-fixed-dim": "#aec6ff",
        "secondary-container": "#75f8b3",
        "surface-dim": "#1f2937",
        "tertiary-container": "#412e00",
        "on-secondary-fixed": "#002111",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "secondary": "#006d43",
        "surface-bright": "#111827",
        "tertiary": "#271a00",
        "tertiary-fixed-dim": "#fbbc00",
        "surface-container": "#1f2937",
        "primary": "#001b44",
        "on-tertiary-container": "#c39100",
        "surface-container-high": "#374151",
        "on-tertiary-fixed": "#261a00",
        "surface": "#111827",
        "inverse-on-surface": "#f2f0f0",
        "secondary-fixed": "#78fbb6",
        "on-secondary": "#ffffff",
        "surface-container-lowest": "#030712",
        "error": "#ba1a1a",
        "on-tertiary-fixed-variant": "#5c4300",
        "on-secondary-container": "#007147",
        "outline-variant": "#4b5563",
        "inverse-primary": "#aec6ff",
        "outline": "#9ca3af",
        "surface-container-highest": "#4b5563",
        "surface-container-low": "#111827",
        "on-error": "#ffffff",
        "primary-fixed": "#d8e2ff",
        "secondary-fixed-dim": "#59de9b",
        "on-background": "#e5e7eb",
        "on-surface-variant": "#d1d5db",
        "inverse-surface": "#303030",
        "on-tertiary": "#ffffff",
        "tertiary-fixed": "#ffdfa0",
        "on-primary-container": "#7999dc",
        "surface-tint": "#3c5d9c",
        "on-surface": "#e5e7eb",
        "on-primary-fixed": "#001a42"
      },
      fontFamily: {
        "headline": ["Manrope"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
      borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
    },
  },
  plugins: [],
}
